apiVersion: v1
kind: Service

metadata:
  name: senevent-service
  namespace: senevent

spec:
  selector:
    app: senevent

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: ClusterIP