apiVersion: v1
kind: Service

metadata:
  name: senevent-blue-service
  namespace: senevent

  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics.php"
    prometheus.io/port: "80"

spec:
  selector:
    app: senevent
    version: blue

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: ClusterIP