apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - mysql-secret.yaml
  - mysql-pvc.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - app-deployment.yaml
  - app-service.yaml
  - blue-deployment.yaml
  - green-deployment.yaml
  - blue-service.yaml
  - green-service.yaml
  - canary-deployment.yaml
  - canary-service.yaml
  - canary-ingress.yaml
  - ingress.yaml