apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: senevent

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: senevent
  MYSQL_USER: senevent
  MYSQL_PASSWORD: password